# Generated by Django 5.2.4 on 2026-01-15 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("annotation", "0002_alter_label_name_alter_label_unique_together"),
    ]

    operations = []
