# Generated by Django 5.2.4 on 2026-01-15 07:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annotation", "0003_auto_20260115_1336"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Text",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text_id", models.CharField(blank=True, max_length=255)),
                ("text", models.TextField()),
                ("meta", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="texts",
                        to="annotation.project",
                    ),
                ),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="annotation",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="annotation",
            name="text",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="annotations",
                to="annotation.text",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="annotation",
            unique_together={("text", "user", "start_index", "end_index", "label")},
        ),
        migrations.RemoveField(
            model_name="annotation",
            name="document",
        ),
        migrations.DeleteModel(
            name="Document",
        ),
    ]
