# Generated by Django 5.2.4 on 2026-01-18 06:15

from django.db import migrations, models


def migrate_suggestion_to_suggestions(apps, schema_editor):
    Annotation = apps.get_model('annotation', 'Annotation')
    for ann in Annotation.objects.all():
        if ann.suggestion:
            ann.suggestions = [ann.suggestion]
        else:
            ann.suggestions = []
        ann.save()


class Migration(migrations.Migration):

    dependencies = [
        ("annotation", "0004_text_alter_annotation_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='suggestions',
            field=models.JSONField(default=list, blank=True),
        ),
        migrations.RunPython(migrate_suggestion_to_suggestions, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='annotation',
            name='suggestion',
        ),
    ]