# Generated by Django 5.2.4 on 2026-01-18 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annotation", "0005_change_suggestion_to_suggestions"),
    ]

    operations = [
        # Delete annotations with null text (invalid data)
        migrations.RunSQL(
            "DELETE FROM annotation_annotation WHERE text_id IS NULL",
            reverse_sql=migrations.RunSQL.noop,
        ),
        # Alter text field to non-nullable
        migrations.AlterField(
            model_name='annotation',
            name='text',
            field=models.ForeignKey(
                on_delete=models.CASCADE,
                related_name='annotations',
                to='annotation.text'
            ),
        ),
    ]