# Generated by Django 5.2.4 on 2026-01-25 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annotation", "0006_fix_text_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="user_project_id",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
