# Generated by Django 5.2.4 on 2026-01-25 07:05

from django.db import migrations


def populate_user_project_ids(apps, schema_editor):
    Project = apps.get_model('annotation', 'Project')
    # Group projects by owner and order by creation time
    owners = Project.objects.order_by('owner', 'created_at').values('owner').distinct()

    for owner_data in owners:
        owner_id = owner_data['owner']
        projects = Project.objects.filter(owner_id=owner_id).order_by('created_at')

        for index, project in enumerate(projects, start=1):
            project.user_project_id = index
            project.save()


def reverse_populate_user_project_ids(apps, schema_editor):
    # No need for reverse migration as this is one-way data population
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("annotation", "0007_project_user_project_id"),
    ]

    operations = [
        migrations.RunPython(populate_user_project_ids, reverse_populate_user_project_ids),
    ]
