# Generated by Django 5.2.10 on 2026-01-25 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annotation", "0008_populate_user_project_ids"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="user_project_id",
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
