# Generated by Django 5.2.10 on 2026-02-13 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0009_alter_project_user_project_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='error_code',
            field=models.IntegerField(default=0),
        ),
    ]
