# Generated by Django 5.2.10 on 2026-02-13 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0010_label_error_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='error_code',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
